# Generated by Django 2.2.10 on 2020-02-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='telefone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
