# Generated by Django 2.2.10 on 2020-02-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_lead_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersMoskit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_moskit', models.IntegerField()),
                ('email', models.CharField(max_length=80, null=True)),
                ('nome', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Users Moskit',
                'verbose_name': 'User Moskit',
            },
        ),
    ]
