# Generated by Django 2.2.10 on 2020-06-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20200619_0350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Curso/Formação', 'verbose_name_plural': 'Cursos/Formações'},
        ),
        migrations.AlterModelOptions(
            name='userscrm',
            options={'verbose_name': 'Consultor', 'verbose_name_plural': 'Consultores'},
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_turma', models.CharField(max_length=50, null=True)),
                ('periodo', models.CharField(max_length=200, null=True)),
                ('qtd_encontros', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Tag')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contratante', models.CharField(max_length=250, null=True)),
                ('rg', models.CharField(max_length=11, null=True)),
                ('cpf', models.CharField(max_length=14, null=True)),
                ('endereco', models.CharField(max_length=250, null=True)),
                ('cidade_estado', models.CharField(max_length=100, null=True)),
                ('cep', models.CharField(max_length=100, null=True)),
                ('telefone', models.CharField(max_length=100, null=True)),
                ('data_nascimento', models.DateField(null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Tag')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Turma')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
