# Generated by Django 2.2.10 on 2020-06-21 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20200621_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='curso',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.Turma'),
        ),
    ]
