# Generated by Django 2.2.10 on 2020-06-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20200621_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.Tag'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.Tag'),
        ),
    ]
