# Generated by Django 2.2.10 on 2020-06-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_auto_20200621_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cep',
            field=models.CharField(max_length=100, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cidade_estado',
            field=models.CharField(max_length=100, null=True, verbose_name='Cidade/UF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contratante',
            field=models.CharField(max_length=250, null=True, verbose_name='Contratante'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cpf',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='rg',
            field=models.CharField(max_length=11, null=True, verbose_name='RG'),
        ),
    ]
