# Generated by Django 2.2.13 on 2020-06-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_turma_status_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='condicoes_pagamento',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='forma_pagamento',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
