# Generated by Django 2.2.13 on 2020-07-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_auto_20200626_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='extra_bonus',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
