# Generated by Django 2.2.13 on 2020-07-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_contrato_extra_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='url_contrato',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
