# Generated by Django 2.2.13 on 2020-07-07 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_auto_20200706_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='lead',
            new_name='cod_transacao',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tag',
        ),
        migrations.AddField(
            model_name='transaction',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.Contrato'),
        ),
    ]
