ESTADO_CIVIL = [
    ('','Selecione o estado civil'),
    ('1', 'Solteiro/Solteira'),
    ('2', 'Casado/Casada'),
    ('3', 'União Estável'),
    ('4', 'Divorciado/Divorciada'),
    ('5', 'Viúvo/Viúva'),
]

ESTADOS = [
    ('','UF'),
    ('1', 'AC'),
    ('2', 'AL'),
    ('3', 'AP'),
    ('4', 'AM'),
    ('5', 'BA'),
    ('6', 'CE'),
    ('7', 'DF'),
    ('8', 'ES'),
    ('9', 'GO'),
    ('10', 'MA'),
    ('11', 'MT'),
    ('12', 'MS'),
    ('13', 'MG'),
    ('14', 'PA'),
    ('15', 'PB'),
    ('16', 'PR'),
    ('17', 'PE'),
    ('18', 'PI'),
    ('19', 'RJ'),
    ('20', 'RN'),
    ('21', 'RS'),
    ('22', 'RO'),
    ('23', 'RR'),
    ('24', 'SC'),
    ('25', 'SP'),
    ('26', 'SE'),
    ('27', 'TO'),
]
